project_id = "yarjaudctshlxkatqgeb"

[functions.google-calendar-auth]
verify_jwt = false

[functions.outlook-calendar-auth]
verify_jwt = false

[functions.vehicle-lookup]
verify_jwt = false

[functions.sync-calendar-trips]
verify_jwt = false

[functions.recalculate-distances]
verify_jwt = false
