-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2b5ORsAPdldWrkca
E6z8U6TA5i498EazwlWratfU/VKgCgYIKoZIzj0DAQehRANCAAQbsZ75P+/L9WT4
nfNMaRYTfRKnoC/TzuykSnwQzSfjL/HWoB6+aOa/uMsnoD3LxohJyadWbSln1Kpf
m4xaDjKE
-----END PRIVATE KEY-----