/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquisitionDeClientsRouteImport } from './routes/acquisition-de-clients'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as ArtisansRouteImport } from './routes/artisans'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BaremeIk2026RouteImport } from './routes/bareme-ik-2026'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as ComparatifDriversnoteRouteImport } from './routes/comparatif-driversnote'
import { Route as ComparatifIzikaRouteImport } from './routes/comparatif-izika'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevisChantierRouteImport } from './routes/devis-chantier'
import { Route as ExpertComptableRouteImport } from './routes/expert-comptable'
import { Route as ExpertsComptablesRouteImport } from './routes/experts-comptables'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as FraisReelsRouteImport } from './routes/frais-reels'
import { Route as IndemniteGrandDeplacement2026RouteImport } from './routes/indemnite-grand-deplacement-2026'
import { Route as IndemniteKilometriqueVeloRouteImport } from './routes/indemnite-kilometrique-velo'
import { Route as IndependantsRouteImport } from './routes/independants'
import { Route as IndChar233pendantsRouteImport } from './routes/indépendants'
import { Route as InstallRouteImport } from './routes/install'
import { Route as InstallerRouteImport } from './routes/installer'
import { Route as LexiqueRouteImport } from './routes/lexique'
import { Route as MarinaRouteImport } from './routes/marina'
import { Route as MeilleureApplicationIndemnitesKilometriquesRouteImport } from './routes/meilleure-application-indemnites-kilometriques'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MesTrajetsRouteImport } from './routes/mes-trajets'
import { Route as MestrajetsRouteImport } from './routes/mestrajets'
import { Route as ModeTourneeRouteImport } from './routes/mode-tournee'
import { Route as NoteDeFraisKilometriqueRouteImport } from './routes/note-de-frais-kilometrique'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RgpdRouteImport } from './routes/rgpd'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThemeOnboardingRouteImport } from './routes/theme-onboarding'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppArchiveRouteImport } from './routes/app/archive'
import { Route as AppMestrajetsRouteImport } from './routes/app/mestrajets'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRecoveryRouteImport } from './routes/app/recovery'
import { Route as AppThemeOnboardingRouteImport } from './routes/app/theme-onboarding'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DebugTourModalRouteImport } from './routes/debug/tour-modal'
import { Route as TemporaryreportIdRouteImport } from './routes/temporaryreport/$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminPartnersRouteImport } from './routes/app/admin/partners'
import { Route as BlogAuteurSlugRouteImport } from './routes/blog/auteur/$slug'
import { Route as BlogEditIndexRouteImport } from './routes/blog/edit/index'
import { Route as BlogEditIdRouteImport } from './routes/blog/edit/$id'
import { Route as AdminBlogEditIndexRouteImport } from './routes/admin/blog/edit/index'
import { Route as AdminBlogEditIdRouteImport } from './routes/admin/blog/edit/$id'
import { Route as AppAdminBlogIndexRouteImport } from './routes/app/admin/blog/index'
import { Route as AppAdminBlogEditIndexRouteImport } from './routes/app/admin/blog/edit/index'
import { Route as AppAdminBlogEditIdRouteImport } from './routes/app/admin/blog/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionDeClientsRoute = AcquisitionDeClientsRouteImport.update({
  id: '/acquisition-de-clients',
  path: '/acquisition-de-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansRoute = ArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaremeIk2026Route = BaremeIk2026RouteImport.update({
  id: '/bareme-ik-2026',
  path: '/bareme-ik-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifDriversnoteRoute = ComparatifDriversnoteRouteImport.update({
  id: '/comparatif-driversnote',
  path: '/comparatif-driversnote',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifIzikaRoute = ComparatifIzikaRouteImport.update({
  id: '/comparatif-izika',
  path: '/comparatif-izika',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisChantierRoute = DevisChantierRouteImport.update({
  id: '/devis-chantier',
  path: '/devis-chantier',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertComptableRoute = ExpertComptableRouteImport.update({
  id: '/expert-comptable',
  path: '/expert-comptable',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsComptablesRoute = ExpertsComptablesRouteImport.update({
  id: '/experts-comptables',
  path: '/experts-comptables',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const FraisReelsRoute = FraisReelsRouteImport.update({
  id: '/frais-reels',
  path: '/frais-reels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndemniteGrandDeplacement2026Route =
  IndemniteGrandDeplacement2026RouteImport.update({
    id: '/indemnite-grand-deplacement-2026',
    path: '/indemnite-grand-deplacement-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndemniteKilometriqueVeloRoute =
  IndemniteKilometriqueVeloRouteImport.update({
    id: '/indemnite-kilometrique-velo',
    path: '/indemnite-kilometrique-velo',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndependantsRoute = IndependantsRouteImport.update({
  id: '/independants',
  path: '/independants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndChar233pendantsRoute = IndChar233pendantsRouteImport.update({
  id: '/indépendants',
  path: '/indépendants',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallerRoute = InstallerRouteImport.update({
  id: '/installer',
  path: '/installer',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiqueRoute = LexiqueRouteImport.update({
  id: '/lexique',
  path: '/lexique',
  getParentRoute: () => rootRouteImport,
} as any)
const MarinaRoute = MarinaRouteImport.update({
  id: '/marina',
  path: '/marina',
  getParentRoute: () => rootRouteImport,
} as any)
const MeilleureApplicationIndemnitesKilometriquesRoute =
  MeilleureApplicationIndemnitesKilometriquesRouteImport.update({
    id: '/meilleure-application-indemnites-kilometriques',
    path: '/meilleure-application-indemnites-kilometriques',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MesTrajetsRoute = MesTrajetsRouteImport.update({
  id: '/mes-trajets',
  path: '/mes-trajets',
  getParentRoute: () => rootRouteImport,
} as any)
const MestrajetsRoute = MestrajetsRouteImport.update({
  id: '/mestrajets',
  path: '/mestrajets',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeTourneeRoute = ModeTourneeRouteImport.update({
  id: '/mode-tournee',
  path: '/mode-tournee',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteDeFraisKilometriqueRoute = NoteDeFraisKilometriqueRouteImport.update({
  id: '/note-de-frais-kilometrique',
  path: '/note-de-frais-kilometrique',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpdRoute = RgpdRouteImport.update({
  id: '/rgpd',
  path: '/rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeOnboardingRoute = ThemeOnboardingRouteImport.update({
  id: '/theme-onboarding',
  path: '/theme-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/app/archive',
  path: '/app/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMestrajetsRoute = AppMestrajetsRouteImport.update({
  id: '/app/mestrajets',
  path: '/app/mestrajets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecoveryRoute = AppRecoveryRouteImport.update({
  id: '/app/recovery',
  path: '/app/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThemeOnboardingRoute = AppThemeOnboardingRouteImport.update({
  id: '/app/theme-onboarding',
  path: '/app/theme-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTourModalRoute = DebugTourModalRouteImport.update({
  id: '/debug/tour-modal',
  path: '/debug/tour-modal',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporaryreportIdRoute = TemporaryreportIdRouteImport.update({
  id: '/temporaryreport/$id',
  path: '/temporaryreport/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/app/admin/',
  path: '/app/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminPartnersRoute = AppAdminPartnersRouteImport.update({
  id: '/app/admin/partners',
  path: '/app/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuteurSlugRoute = BlogAuteurSlugRouteImport.update({
  id: '/blog/auteur/$slug',
  path: '/blog/auteur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditIndexRoute = BlogEditIndexRouteImport.update({
  id: '/blog/edit/',
  path: '/blog/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditIdRoute = BlogEditIdRouteImport.update({
  id: '/blog/edit/$id',
  path: '/blog/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogEditIndexRoute = AdminBlogEditIndexRouteImport.update({
  id: '/admin/blog/edit/',
  path: '/admin/blog/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogEditIdRoute = AdminBlogEditIdRouteImport.update({
  id: '/admin/blog/edit/$id',
  path: '/admin/blog/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBlogIndexRoute = AppAdminBlogIndexRouteImport.update({
  id: '/app/admin/blog/',
  path: '/app/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBlogEditIndexRoute = AppAdminBlogEditIndexRouteImport.update({
  id: '/app/admin/blog/edit/',
  path: '/app/admin/blog/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBlogEditIdRoute = AppAdminBlogEditIdRouteImport.update({
  id: '/app/admin/blog/edit/$id',
  path: '/app/admin/blog/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisition-de-clients': typeof AcquisitionDeClientsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/bareme-ik-2026': typeof BaremeIk2026Route
  '/calendrier': typeof CalendrierRoute
  '/comparatif-driversnote': typeof ComparatifDriversnoteRoute
  '/comparatif-izika': typeof ComparatifIzikaRoute
  '/contact': typeof ContactRoute
  '/devis-chantier': typeof DevisChantierRoute
  '/expert-comptable': typeof ExpertComptableRoute
  '/experts-comptables': typeof ExpertsComptablesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/frais-reels': typeof FraisReelsRoute
  '/indemnite-grand-deplacement-2026': typeof IndemniteGrandDeplacement2026Route
  '/indemnite-kilometrique-velo': typeof IndemniteKilometriqueVeloRoute
  '/independants': typeof IndependantsRoute
  '/indépendants': typeof IndChar233pendantsRoute
  '/install': typeof InstallRoute
  '/installer': typeof InstallerRoute
  '/lexique': typeof LexiqueRoute
  '/marina': typeof MarinaRoute
  '/meilleure-application-indemnites-kilometriques': typeof MeilleureApplicationIndemnitesKilometriquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-trajets': typeof MesTrajetsRoute
  '/mestrajets': typeof MestrajetsRoute
  '/mode-tournee': typeof ModeTourneeRoute
  '/note-de-frais-kilometrique': typeof NoteDeFraisKilometriqueRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/report': typeof ReportRoute
  '/rgpd': typeof RgpdRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/theme-onboarding': typeof ThemeOnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/mestrajets': typeof AppMestrajetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/theme-onboarding': typeof AppThemeOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/debug/tour-modal': typeof DebugTourModalRoute
  '/temporaryreport/$id': typeof TemporaryreportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/blog/auteur/$slug': typeof BlogAuteurSlugRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/blog/edit/': typeof BlogEditIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
  '/admin/blog/edit/': typeof AdminBlogEditIndexRoute
  '/app/admin/blog/': typeof AppAdminBlogIndexRoute
  '/app/admin/blog/edit/$id': typeof AppAdminBlogEditIdRoute
  '/app/admin/blog/edit/': typeof AppAdminBlogEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisition-de-clients': typeof AcquisitionDeClientsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/bareme-ik-2026': typeof BaremeIk2026Route
  '/calendrier': typeof CalendrierRoute
  '/comparatif-driversnote': typeof ComparatifDriversnoteRoute
  '/comparatif-izika': typeof ComparatifIzikaRoute
  '/contact': typeof ContactRoute
  '/devis-chantier': typeof DevisChantierRoute
  '/expert-comptable': typeof ExpertComptableRoute
  '/experts-comptables': typeof ExpertsComptablesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/frais-reels': typeof FraisReelsRoute
  '/indemnite-grand-deplacement-2026': typeof IndemniteGrandDeplacement2026Route
  '/indemnite-kilometrique-velo': typeof IndemniteKilometriqueVeloRoute
  '/independants': typeof IndependantsRoute
  '/indépendants': typeof IndChar233pendantsRoute
  '/install': typeof InstallRoute
  '/installer': typeof InstallerRoute
  '/lexique': typeof LexiqueRoute
  '/marina': typeof MarinaRoute
  '/meilleure-application-indemnites-kilometriques': typeof MeilleureApplicationIndemnitesKilometriquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-trajets': typeof MesTrajetsRoute
  '/mestrajets': typeof MestrajetsRoute
  '/mode-tournee': typeof ModeTourneeRoute
  '/note-de-frais-kilometrique': typeof NoteDeFraisKilometriqueRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/report': typeof ReportRoute
  '/rgpd': typeof RgpdRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/theme-onboarding': typeof ThemeOnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/mestrajets': typeof AppMestrajetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/theme-onboarding': typeof AppThemeOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/debug/tour-modal': typeof DebugTourModalRoute
  '/temporaryreport/$id': typeof TemporaryreportIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/blog/auteur/$slug': typeof BlogAuteurSlugRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/blog/edit': typeof BlogEditIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
  '/admin/blog/edit': typeof AdminBlogEditIndexRoute
  '/app/admin/blog': typeof AppAdminBlogIndexRoute
  '/app/admin/blog/edit/$id': typeof AppAdminBlogEditIdRoute
  '/app/admin/blog/edit': typeof AppAdminBlogEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisition-de-clients': typeof AcquisitionDeClientsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/bareme-ik-2026': typeof BaremeIk2026Route
  '/calendrier': typeof CalendrierRoute
  '/comparatif-driversnote': typeof ComparatifDriversnoteRoute
  '/comparatif-izika': typeof ComparatifIzikaRoute
  '/contact': typeof ContactRoute
  '/devis-chantier': typeof DevisChantierRoute
  '/expert-comptable': typeof ExpertComptableRoute
  '/experts-comptables': typeof ExpertsComptablesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/frais-reels': typeof FraisReelsRoute
  '/indemnite-grand-deplacement-2026': typeof IndemniteGrandDeplacement2026Route
  '/indemnite-kilometrique-velo': typeof IndemniteKilometriqueVeloRoute
  '/independants': typeof IndependantsRoute
  '/indépendants': typeof IndChar233pendantsRoute
  '/install': typeof InstallRoute
  '/installer': typeof InstallerRoute
  '/lexique': typeof LexiqueRoute
  '/marina': typeof MarinaRoute
  '/meilleure-application-indemnites-kilometriques': typeof MeilleureApplicationIndemnitesKilometriquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-trajets': typeof MesTrajetsRoute
  '/mestrajets': typeof MestrajetsRoute
  '/mode-tournee': typeof ModeTourneeRoute
  '/note-de-frais-kilometrique': typeof NoteDeFraisKilometriqueRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/report': typeof ReportRoute
  '/rgpd': typeof RgpdRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso': typeof SsoRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/theme-onboarding': typeof ThemeOnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/mestrajets': typeof AppMestrajetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/theme-onboarding': typeof AppThemeOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/debug/tour-modal': typeof DebugTourModalRoute
  '/temporaryreport/$id': typeof TemporaryreportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/blog/auteur/$slug': typeof BlogAuteurSlugRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/blog/edit/': typeof BlogEditIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
  '/admin/blog/edit/': typeof AdminBlogEditIndexRoute
  '/app/admin/blog/': typeof AppAdminBlogIndexRoute
  '/app/admin/blog/edit/$id': typeof AppAdminBlogEditIdRoute
  '/app/admin/blog/edit/': typeof AppAdminBlogEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisition-de-clients'
    | '/api-docs'
    | '/artisans'
    | '/auth'
    | '/bareme-ik-2026'
    | '/calendrier'
    | '/comparatif-driversnote'
    | '/comparatif-izika'
    | '/contact'
    | '/devis-chantier'
    | '/expert-comptable'
    | '/experts-comptables'
    | '/fonctionnalites'
    | '/frais-reels'
    | '/indemnite-grand-deplacement-2026'
    | '/indemnite-kilometrique-velo'
    | '/independants'
    | '/indépendants'
    | '/install'
    | '/installer'
    | '/lexique'
    | '/marina'
    | '/meilleure-application-indemnites-kilometriques'
    | '/mentions-legales'
    | '/mes-trajets'
    | '/mestrajets'
    | '/mode-tournee'
    | '/note-de-frais-kilometrique'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/report'
    | '/rgpd'
    | '/signup'
    | '/sitemap.xml'
    | '/sso'
    | '/tarifs'
    | '/terms'
    | '/theme-onboarding'
    | '/unsubscribe'
    | '/app/archive'
    | '/app/mestrajets'
    | '/app/profile'
    | '/app/recovery'
    | '/app/theme-onboarding'
    | '/blog/$slug'
    | '/debug/tour-modal'
    | '/temporaryreport/$id'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/app/admin/partners'
    | '/blog/auteur/$slug'
    | '/blog/edit/$id'
    | '/admin/blog/'
    | '/app/admin/'
    | '/blog/edit/'
    | '/admin/blog/edit/$id'
    | '/admin/blog/edit/'
    | '/app/admin/blog/'
    | '/app/admin/blog/edit/$id'
    | '/app/admin/blog/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisition-de-clients'
    | '/api-docs'
    | '/artisans'
    | '/auth'
    | '/bareme-ik-2026'
    | '/calendrier'
    | '/comparatif-driversnote'
    | '/comparatif-izika'
    | '/contact'
    | '/devis-chantier'
    | '/expert-comptable'
    | '/experts-comptables'
    | '/fonctionnalites'
    | '/frais-reels'
    | '/indemnite-grand-deplacement-2026'
    | '/indemnite-kilometrique-velo'
    | '/independants'
    | '/indépendants'
    | '/install'
    | '/installer'
    | '/lexique'
    | '/marina'
    | '/meilleure-application-indemnites-kilometriques'
    | '/mentions-legales'
    | '/mes-trajets'
    | '/mestrajets'
    | '/mode-tournee'
    | '/note-de-frais-kilometrique'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/report'
    | '/rgpd'
    | '/signup'
    | '/sitemap.xml'
    | '/sso'
    | '/tarifs'
    | '/terms'
    | '/theme-onboarding'
    | '/unsubscribe'
    | '/app/archive'
    | '/app/mestrajets'
    | '/app/profile'
    | '/app/recovery'
    | '/app/theme-onboarding'
    | '/blog/$slug'
    | '/debug/tour-modal'
    | '/temporaryreport/$id'
    | '/admin'
    | '/app'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/app/admin/partners'
    | '/blog/auteur/$slug'
    | '/blog/edit/$id'
    | '/admin/blog'
    | '/app/admin'
    | '/blog/edit'
    | '/admin/blog/edit/$id'
    | '/admin/blog/edit'
    | '/app/admin/blog'
    | '/app/admin/blog/edit/$id'
    | '/app/admin/blog/edit'
  id:
    | '__root__'
    | '/'
    | '/acquisition-de-clients'
    | '/api-docs'
    | '/artisans'
    | '/auth'
    | '/bareme-ik-2026'
    | '/calendrier'
    | '/comparatif-driversnote'
    | '/comparatif-izika'
    | '/contact'
    | '/devis-chantier'
    | '/expert-comptable'
    | '/experts-comptables'
    | '/fonctionnalites'
    | '/frais-reels'
    | '/indemnite-grand-deplacement-2026'
    | '/indemnite-kilometrique-velo'
    | '/independants'
    | '/indépendants'
    | '/install'
    | '/installer'
    | '/lexique'
    | '/marina'
    | '/meilleure-application-indemnites-kilometriques'
    | '/mentions-legales'
    | '/mes-trajets'
    | '/mestrajets'
    | '/mode-tournee'
    | '/note-de-frais-kilometrique'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/report'
    | '/rgpd'
    | '/signup'
    | '/sitemap.xml'
    | '/sso'
    | '/tarifs'
    | '/terms'
    | '/theme-onboarding'
    | '/unsubscribe'
    | '/app/archive'
    | '/app/mestrajets'
    | '/app/profile'
    | '/app/recovery'
    | '/app/theme-onboarding'
    | '/blog/$slug'
    | '/debug/tour-modal'
    | '/temporaryreport/$id'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/app/admin/partners'
    | '/blog/auteur/$slug'
    | '/blog/edit/$id'
    | '/admin/blog/'
    | '/app/admin/'
    | '/blog/edit/'
    | '/admin/blog/edit/$id'
    | '/admin/blog/edit/'
    | '/app/admin/blog/'
    | '/app/admin/blog/edit/$id'
    | '/app/admin/blog/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionDeClientsRoute: typeof AcquisitionDeClientsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ArtisansRoute: typeof ArtisansRoute
  AuthRoute: typeof AuthRoute
  BaremeIk2026Route: typeof BaremeIk2026Route
  CalendrierRoute: typeof CalendrierRoute
  ComparatifDriversnoteRoute: typeof ComparatifDriversnoteRoute
  ComparatifIzikaRoute: typeof ComparatifIzikaRoute
  ContactRoute: typeof ContactRoute
  DevisChantierRoute: typeof DevisChantierRoute
  ExpertComptableRoute: typeof ExpertComptableRoute
  ExpertsComptablesRoute: typeof ExpertsComptablesRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  FraisReelsRoute: typeof FraisReelsRoute
  IndemniteGrandDeplacement2026Route: typeof IndemniteGrandDeplacement2026Route
  IndemniteKilometriqueVeloRoute: typeof IndemniteKilometriqueVeloRoute
  IndependantsRoute: typeof IndependantsRoute
  IndChar233pendantsRoute: typeof IndChar233pendantsRoute
  InstallRoute: typeof InstallRoute
  InstallerRoute: typeof InstallerRoute
  LexiqueRoute: typeof LexiqueRoute
  MarinaRoute: typeof MarinaRoute
  MeilleureApplicationIndemnitesKilometriquesRoute: typeof MeilleureApplicationIndemnitesKilometriquesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesTrajetsRoute: typeof MesTrajetsRoute
  MestrajetsRoute: typeof MestrajetsRoute
  ModeTourneeRoute: typeof ModeTourneeRoute
  NoteDeFraisKilometriqueRoute: typeof NoteDeFraisKilometriqueRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecoveryRoute: typeof RecoveryRoute
  ReportRoute: typeof ReportRoute
  RgpdRoute: typeof RgpdRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SsoRoute: typeof SsoRoute
  TarifsRoute: typeof TarifsRoute
  TermsRoute: typeof TermsRoute
  ThemeOnboardingRoute: typeof ThemeOnboardingRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppMestrajetsRoute: typeof AppMestrajetsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecoveryRoute: typeof AppRecoveryRoute
  AppThemeOnboardingRoute: typeof AppThemeOnboardingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DebugTourModalRoute: typeof DebugTourModalRoute
  TemporaryreportIdRoute: typeof TemporaryreportIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  AppAdminPartnersRoute: typeof AppAdminPartnersRoute
  BlogAuteurSlugRoute: typeof BlogAuteurSlugRoute
  BlogEditIdRoute: typeof BlogEditIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  BlogEditIndexRoute: typeof BlogEditIndexRoute
  AdminBlogEditIdRoute: typeof AdminBlogEditIdRoute
  AdminBlogEditIndexRoute: typeof AdminBlogEditIndexRoute
  AppAdminBlogIndexRoute: typeof AppAdminBlogIndexRoute
  AppAdminBlogEditIdRoute: typeof AppAdminBlogEditIdRoute
  AppAdminBlogEditIndexRoute: typeof AppAdminBlogEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisition-de-clients': {
      id: '/acquisition-de-clients'
      path: '/acquisition-de-clients'
      fullPath: '/acquisition-de-clients'
      preLoaderRoute: typeof AcquisitionDeClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans': {
      id: '/artisans'
      path: '/artisans'
      fullPath: '/artisans'
      preLoaderRoute: typeof ArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bareme-ik-2026': {
      id: '/bareme-ik-2026'
      path: '/bareme-ik-2026'
      fullPath: '/bareme-ik-2026'
      preLoaderRoute: typeof BaremeIk2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatif-driversnote': {
      id: '/comparatif-driversnote'
      path: '/comparatif-driversnote'
      fullPath: '/comparatif-driversnote'
      preLoaderRoute: typeof ComparatifDriversnoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatif-izika': {
      id: '/comparatif-izika'
      path: '/comparatif-izika'
      fullPath: '/comparatif-izika'
      preLoaderRoute: typeof ComparatifIzikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis-chantier': {
      id: '/devis-chantier'
      path: '/devis-chantier'
      fullPath: '/devis-chantier'
      preLoaderRoute: typeof DevisChantierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-comptable': {
      id: '/expert-comptable'
      path: '/expert-comptable'
      fullPath: '/expert-comptable'
      preLoaderRoute: typeof ExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts-comptables': {
      id: '/experts-comptables'
      path: '/experts-comptables'
      fullPath: '/experts-comptables'
      preLoaderRoute: typeof ExpertsComptablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frais-reels': {
      id: '/frais-reels'
      path: '/frais-reels'
      fullPath: '/frais-reels'
      preLoaderRoute: typeof FraisReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indemnite-grand-deplacement-2026': {
      id: '/indemnite-grand-deplacement-2026'
      path: '/indemnite-grand-deplacement-2026'
      fullPath: '/indemnite-grand-deplacement-2026'
      preLoaderRoute: typeof IndemniteGrandDeplacement2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indemnite-kilometrique-velo': {
      id: '/indemnite-kilometrique-velo'
      path: '/indemnite-kilometrique-velo'
      fullPath: '/indemnite-kilometrique-velo'
      preLoaderRoute: typeof IndemniteKilometriqueVeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/independants': {
      id: '/independants'
      path: '/independants'
      fullPath: '/independants'
      preLoaderRoute: typeof IndependantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indépendants': {
      id: '/indépendants'
      path: '/indépendants'
      fullPath: '/indépendants'
      preLoaderRoute: typeof IndChar233pendantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installer': {
      id: '/installer'
      path: '/installer'
      fullPath: '/installer'
      preLoaderRoute: typeof InstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexique': {
      id: '/lexique'
      path: '/lexique'
      fullPath: '/lexique'
      preLoaderRoute: typeof LexiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marina': {
      id: '/marina'
      path: '/marina'
      fullPath: '/marina'
      preLoaderRoute: typeof MarinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meilleure-application-indemnites-kilometriques': {
      id: '/meilleure-application-indemnites-kilometriques'
      path: '/meilleure-application-indemnites-kilometriques'
      fullPath: '/meilleure-application-indemnites-kilometriques'
      preLoaderRoute: typeof MeilleureApplicationIndemnitesKilometriquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-trajets': {
      id: '/mes-trajets'
      path: '/mes-trajets'
      fullPath: '/mes-trajets'
      preLoaderRoute: typeof MesTrajetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestrajets': {
      id: '/mestrajets'
      path: '/mestrajets'
      fullPath: '/mestrajets'
      preLoaderRoute: typeof MestrajetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-tournee': {
      id: '/mode-tournee'
      path: '/mode-tournee'
      fullPath: '/mode-tournee'
      preLoaderRoute: typeof ModeTourneeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-de-frais-kilometrique': {
      id: '/note-de-frais-kilometrique'
      path: '/note-de-frais-kilometrique'
      fullPath: '/note-de-frais-kilometrique'
      preLoaderRoute: typeof NoteDeFraisKilometriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgpd': {
      id: '/rgpd'
      path: '/rgpd'
      fullPath: '/rgpd'
      preLoaderRoute: typeof RgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-onboarding': {
      id: '/theme-onboarding'
      path: '/theme-onboarding'
      fullPath: '/theme-onboarding'
      preLoaderRoute: typeof ThemeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/archive': {
      id: '/app/archive'
      path: '/app/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mestrajets': {
      id: '/app/mestrajets'
      path: '/app/mestrajets'
      fullPath: '/app/mestrajets'
      preLoaderRoute: typeof AppMestrajetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recovery': {
      id: '/app/recovery'
      path: '/app/recovery'
      fullPath: '/app/recovery'
      preLoaderRoute: typeof AppRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/theme-onboarding': {
      id: '/app/theme-onboarding'
      path: '/app/theme-onboarding'
      fullPath: '/app/theme-onboarding'
      preLoaderRoute: typeof AppThemeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/tour-modal': {
      id: '/debug/tour-modal'
      path: '/debug/tour-modal'
      fullPath: '/debug/tour-modal'
      preLoaderRoute: typeof DebugTourModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporaryreport/$id': {
      id: '/temporaryreport/$id'
      path: '/temporaryreport/$id'
      fullPath: '/temporaryreport/$id'
      preLoaderRoute: typeof TemporaryreportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/partners': {
      id: '/app/admin/partners'
      path: '/app/admin/partners'
      fullPath: '/app/admin/partners'
      preLoaderRoute: typeof AppAdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/auteur/$slug': {
      id: '/blog/auteur/$slug'
      path: '/blog/auteur/$slug'
      fullPath: '/blog/auteur/$slug'
      preLoaderRoute: typeof BlogAuteurSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/edit/': {
      id: '/blog/edit/'
      path: '/blog/edit'
      fullPath: '/blog/edit/'
      preLoaderRoute: typeof BlogEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/edit/$id': {
      id: '/blog/edit/$id'
      path: '/blog/edit/$id'
      fullPath: '/blog/edit/$id'
      preLoaderRoute: typeof BlogEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/edit/': {
      id: '/admin/blog/edit/'
      path: '/admin/blog/edit'
      fullPath: '/admin/blog/edit/'
      preLoaderRoute: typeof AdminBlogEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/edit/$id': {
      id: '/admin/blog/edit/$id'
      path: '/admin/blog/edit/$id'
      fullPath: '/admin/blog/edit/$id'
      preLoaderRoute: typeof AdminBlogEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/blog/': {
      id: '/app/admin/blog/'
      path: '/app/admin/blog'
      fullPath: '/app/admin/blog/'
      preLoaderRoute: typeof AppAdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/blog/edit/': {
      id: '/app/admin/blog/edit/'
      path: '/app/admin/blog/edit'
      fullPath: '/app/admin/blog/edit/'
      preLoaderRoute: typeof AppAdminBlogEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/blog/edit/$id': {
      id: '/app/admin/blog/edit/$id'
      path: '/app/admin/blog/edit/$id'
      fullPath: '/app/admin/blog/edit/$id'
      preLoaderRoute: typeof AppAdminBlogEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionDeClientsRoute: AcquisitionDeClientsRoute,
  ApiDocsRoute: ApiDocsRoute,
  ArtisansRoute: ArtisansRoute,
  AuthRoute: AuthRoute,
  BaremeIk2026Route: BaremeIk2026Route,
  CalendrierRoute: CalendrierRoute,
  ComparatifDriversnoteRoute: ComparatifDriversnoteRoute,
  ComparatifIzikaRoute: ComparatifIzikaRoute,
  ContactRoute: ContactRoute,
  DevisChantierRoute: DevisChantierRoute,
  ExpertComptableRoute: ExpertComptableRoute,
  ExpertsComptablesRoute: ExpertsComptablesRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  FraisReelsRoute: FraisReelsRoute,
  IndemniteGrandDeplacement2026Route: IndemniteGrandDeplacement2026Route,
  IndemniteKilometriqueVeloRoute: IndemniteKilometriqueVeloRoute,
  IndependantsRoute: IndependantsRoute,
  IndChar233pendantsRoute: IndChar233pendantsRoute,
  InstallRoute: InstallRoute,
  InstallerRoute: InstallerRoute,
  LexiqueRoute: LexiqueRoute,
  MarinaRoute: MarinaRoute,
  MeilleureApplicationIndemnitesKilometriquesRoute:
    MeilleureApplicationIndemnitesKilometriquesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesTrajetsRoute: MesTrajetsRoute,
  MestrajetsRoute: MestrajetsRoute,
  ModeTourneeRoute: ModeTourneeRoute,
  NoteDeFraisKilometriqueRoute: NoteDeFraisKilometriqueRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecoveryRoute: RecoveryRoute,
  ReportRoute: ReportRoute,
  RgpdRoute: RgpdRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SsoRoute: SsoRoute,
  TarifsRoute: TarifsRoute,
  TermsRoute: TermsRoute,
  ThemeOnboardingRoute: ThemeOnboardingRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppMestrajetsRoute: AppMestrajetsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecoveryRoute: AppRecoveryRoute,
  AppThemeOnboardingRoute: AppThemeOnboardingRoute,
  BlogSlugRoute: BlogSlugRoute,
  DebugTourModalRoute: DebugTourModalRoute,
  TemporaryreportIdRoute: TemporaryreportIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  AppAdminPartnersRoute: AppAdminPartnersRoute,
  BlogAuteurSlugRoute: BlogAuteurSlugRoute,
  BlogEditIdRoute: BlogEditIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  BlogEditIndexRoute: BlogEditIndexRoute,
  AdminBlogEditIdRoute: AdminBlogEditIdRoute,
  AdminBlogEditIndexRoute: AdminBlogEditIndexRoute,
  AppAdminBlogIndexRoute: AppAdminBlogIndexRoute,
  AppAdminBlogEditIdRoute: AppAdminBlogEditIdRoute,
  AppAdminBlogEditIndexRoute: AppAdminBlogEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
