// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-vehicles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vehicles_default = defineTool({
  name: "list_vehicles",
  title: "Lister mes v\xE9hicules",
  description: "Retourne la liste des v\xE9hicules IKtracker de l'utilisateur (nom, marque, mod\xE8le, chevaux fiscaux, \xE9lectrique, immatriculation).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("vehicles").select("id, name, make, model, year, fiscal_power, is_electric, license_plate").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trips.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trips_default = defineTool2({
  name: "list_trips",
  title: "Lister mes trajets",
  description: "Retourne les trajets IKtracker de l'utilisateur, filtrables par plage de dates (YYYY-MM-DD) et par v\xE9hicule. Limite par d\xE9faut : 50, max 200.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date de d\xE9but incluse (YYYY-MM-DD)."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date de fin incluse (YYYY-MM-DD)."),
    vehicle_id: z.string().uuid().optional().describe("Filtrer sur un v\xE9hicule."),
    limit: z.number().int().min(1).max(200).optional().describe("Nombre max de trajets (d\xE9faut 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, vehicle_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    let q = sb2(ctx).from("trips").select("id, date, start_location, end_location, distance, round_trip, ik_amount, purpose, vehicle_id, status").is("deleted_at", null).order("date", { ascending: false }).limit(limit ?? 50);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (vehicle_id) q = q.eq("vehicle_id", vehicle_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trips: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-ytd-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_ytd_summary_default = defineTool3({
  name: "get_ytd_summary",
  title: "Synth\xE8se annuelle IK",
  description: "Retourne le cumul kilom\xE9trique et l'indemnit\xE9 totale par v\xE9hicule pour une ann\xE9e donn\xE9e (ann\xE9e en cours par d\xE9faut).",
  inputSchema: {
    year: z2.number().int().min(2e3).max(2100).optional().describe("Ann\xE9e civile (d\xE9faut : ann\xE9e courante).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const y = year ?? (/* @__PURE__ */ new Date()).getFullYear();
    const from = `${y}-01-01`;
    const to = `${y}-12-31`;
    const client = sb3(ctx);
    const [{ data: trips, error: e1 }, { data: vehicles, error: e2 }] = await Promise.all([
      client.from("trips").select("vehicle_id, distance, ik_amount").is("deleted_at", null).gte("date", from).lte("date", to),
      client.from("vehicles").select("id, name, make, model, fiscal_power, is_electric")
    ]);
    if (e1 || e2) {
      return { content: [{ type: "text", text: (e1 ?? e2).message }], isError: true };
    }
    const byVehicle = /* @__PURE__ */ new Map();
    for (const t of trips ?? []) {
      const key = t.vehicle_id;
      const acc = byVehicle.get(key) ?? { distance: 0, ik_amount: 0, trips: 0 };
      acc.distance += Number(t.distance ?? 0);
      acc.ik_amount += Number(t.ik_amount ?? 0);
      acc.trips += 1;
      byVehicle.set(key, acc);
    }
    const perVehicle = (vehicles ?? []).map((v) => {
      const s = byVehicle.get(v.id) ?? { distance: 0, ik_amount: 0, trips: 0 };
      return {
        vehicle_id: v.id,
        vehicle: [v.make, v.model].filter(Boolean).join(" ") || v.name,
        fiscal_power: v.fiscal_power,
        is_electric: v.is_electric,
        total_km: Math.round(s.distance * 100) / 100,
        total_ik_eur: Math.round(s.ik_amount * 100) / 100,
        trip_count: s.trips
      };
    });
    const total = perVehicle.reduce(
      (acc, v) => ({
        total_km: acc.total_km + v.total_km,
        total_ik_eur: acc.total_ik_eur + v.total_ik_eur,
        trip_count: acc.trip_count + v.trip_count
      }),
      { total_km: 0, total_ik_eur: 0, trip_count: 0 }
    );
    const summary = {
      year: y,
      total_km: Math.round(total.total_km * 100) / 100,
      total_ik_eur: Math.round(total.total_ik_eur * 100) / 100,
      trip_count: total.trip_count,
      per_vehicle: perVehicle
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/create-trip.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.87.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_trip_default = defineTool4({
  name: "create_trip",
  title: "Cr\xE9er un trajet",
  description: "Cr\xE9e un nouveau trajet IKtracker pour l'utilisateur. Le montant IK est laiss\xE9 \xE0 z\xE9ro (recalcul\xE9 c\xF4t\xE9 app) ; renseigner un `ik_amount` explicite si besoin.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Date du trajet (YYYY-MM-DD)."),
    start_location: z3.string().min(1).describe("Adresse ou nom du point de d\xE9part."),
    end_location: z3.string().min(1).describe("Adresse ou nom du point d'arriv\xE9e."),
    distance: z3.number().positive().describe("Distance parcourue en kilom\xE8tres."),
    vehicle_id: z3.string().uuid().optional().describe("V\xE9hicule utilis\xE9 (UUID)."),
    round_trip: z3.boolean().optional().describe("Trajet aller-retour."),
    purpose: z3.string().optional().describe("Motif du d\xE9placement."),
    ik_amount: z3.number().nonnegative().optional().describe("Montant IK en euros (0 par d\xE9faut).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("trips").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      start_location: input.start_location,
      end_location: input.end_location,
      distance: input.distance,
      vehicle_id: input.vehicle_id ?? null,
      round_trip: input.round_trip ?? false,
      purpose: input.purpose ?? null,
      ik_amount: input.ik_amount ?? 0,
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Trajet cr\xE9\xE9 (${data.id})` }],
      structuredContent: { trip: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yarjaudctshlxkatqgeb";
var mcp_default = defineMcp({
  name: "iktracker-mcp",
  title: "IKtracker MCP",
  version: "0.1.0",
  instructions: "Outils IKtracker pour consulter les trajets, v\xE9hicules et cumuls annuels d'indemnit\xE9s kilom\xE9triques de l'utilisateur connect\xE9, et cr\xE9er de nouveaux trajets. Toutes les donn\xE9es sont scop\xE9es \xE0 l'utilisateur authentifi\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_vehicles_default, list_trips_default, get_ytd_summary_default, create_trip_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
